/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssistedKioskRouteImport } from './routes/assisted-kiosk'
import { Route as ClinicianRouteImport } from './routes/clinician'
import { Route as DocumentCheckRouteImport } from './routes/document-check'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as PatientKioskRouteImport } from './routes/patient-kiosk'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminConfigurationRouteImport } from './routes/admin.configuration'
import { Route as AdminFacilitiesRouteImport } from './routes/admin.facilities'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AssistedKioskIndexRouteImport } from './routes/assisted-kiosk.index'
import { Route as AssistedKioskCaseTakingRouteImport } from './routes/assisted-kiosk.case-taking'
import { Route as AssistedKioskDocumentsRouteImport } from './routes/assisted-kiosk.documents'
import { Route as AssistedKioskHandoffRouteImport } from './routes/assisted-kiosk.handoff'
import { Route as AssistedKioskQueueRouteImport } from './routes/assisted-kiosk.queue'
import { Route as AssistedKioskStartRouteImport } from './routes/assisted-kiosk.start'
import { Route as AssistedKioskVitalsRouteImport } from './routes/assisted-kiosk.vitals'
import { Route as ClinicianIndexRouteImport } from './routes/clinician.index'
import { Route as ClinicianAlertsRouteImport } from './routes/clinician.alerts'
import { Route as ClinicianDocumentsRouteImport } from './routes/clinician.documents'
import { Route as ClinicianPatientsRouteImport } from './routes/clinician.patients'
import { Route as ClinicianSettingsRouteImport } from './routes/clinician.settings'
import { Route as ClinicianTimelineRouteImport } from './routes/clinician.timeline'
import { Route as ClinicianWorklistRouteImport } from './routes/clinician.worklist'
import { Route as OperationsIndexRouteImport } from './routes/operations.index'
import { Route as OperationsDlqRouteImport } from './routes/operations.dlq'
import { Route as OperationsManualReviewRouteImport } from './routes/operations.manual-review'
import { Route as OperationsOutboxRouteImport } from './routes/operations.outbox'
import { Route as OperationsReplayRouteImport } from './routes/operations.replay'
import { Route as OperationsSearchRouteImport } from './routes/operations.search'
import { Route as PatientKioskIndexRouteImport } from './routes/patient-kiosk.index'
import { Route as PatientKioskCaseTakingRouteImport } from './routes/patient-kiosk.case-taking'
import { Route as PatientKioskCompleteRouteImport } from './routes/patient-kiosk.complete'
import { Route as PatientKioskConfirmRouteImport } from './routes/patient-kiosk.confirm'
import { Route as PatientKioskConsentRouteImport } from './routes/patient-kiosk.consent'
import { Route as PatientKioskConversationRouteImport } from './routes/patient-kiosk.conversation'
import { Route as PatientKioskDocumentsRouteImport } from './routes/patient-kiosk.documents'
import { Route as PatientKioskIdentificationRouteImport } from './routes/patient-kiosk.identification'
import { Route as PatientKioskIntroductionRouteImport } from './routes/patient-kiosk.introduction'
import { Route as PatientKioskProcessingRouteImport } from './routes/patient-kiosk.processing'
import { Route as PatientKioskQuestionsRouteImport } from './routes/patient-kiosk.questions'
import { Route as PatientKioskReviewRouteImport } from './routes/patient-kiosk.review'
import { Route as PatientKioskVitalsRouteImport } from './routes/patient-kiosk.vitals'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientConsentsRouteImport } from './routes/patient.consents'
import { Route as PatientDocumentsRouteImport } from './routes/patient.documents'
import { Route as PatientIntakesRouteImport } from './routes/patient.intakes'
import { Route as PatientNotificationsRouteImport } from './routes/patient.notifications'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientReportsRouteImport } from './routes/patient.reports'
import { Route as PatientTimelineRouteImport } from './routes/patient.timeline'
import { Route as PatientIntakeRouteImport } from './routes/patient_.intake'
import { Route as ClinicianPatientsIndexRouteImport } from './routes/clinician.patients.index'
import { Route as ClinicianPatientsIdRouteImport } from './routes/clinician.patients.$id'
import { Route as ApiDocumentsDocumentIdFileRouteImport } from './routes/api/documents.$documentId.file'
import { Route as ApiPublicVoiceSpeakRouteImport } from './routes/api/public/voice/speak'
import { Route as ApiPublicVoiceTranscribeRouteImport } from './routes/api/public/voice/transcribe'
import { Route as ClinicianPatientsIdSignRouteImport } from './routes/clinician.patients.$id.sign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistedKioskRoute = AssistedKioskRouteImport.update({
  id: '/assisted-kiosk',
  path: '/assisted-kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicianRoute = ClinicianRouteImport.update({
  id: '/clinician',
  path: '/clinician',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentCheckRoute = DocumentCheckRouteImport.update({
  id: '/document-check',
  path: '/document-check',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientKioskRoute = PatientKioskRouteImport.update({
  id: '/patient-kiosk',
  path: '/patient-kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigurationRoute = AdminConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AssistedKioskIndexRoute = AssistedKioskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssistedKioskRoute,
} as any)
const AssistedKioskCaseTakingRoute = AssistedKioskCaseTakingRouteImport.update({
  id: '/case-taking',
  path: '/case-taking',
  getParentRoute: () => AssistedKioskRoute,
} as any)
const AssistedKioskDocumentsRoute = AssistedKioskDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AssistedKioskRoute,
} as any)
const AssistedKioskHandoffRoute = AssistedKioskHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => AssistedKioskRoute,
} as any)
const AssistedKioskQueueRoute = AssistedKioskQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AssistedKioskRoute,
} as any)
const AssistedKioskStartRoute = AssistedKioskStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AssistedKioskRoute,
} as any)
const AssistedKioskVitalsRoute = AssistedKioskVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AssistedKioskRoute,
} as any)
const ClinicianIndexRoute = ClinicianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicianRoute,
} as any)
const ClinicianAlertsRoute = ClinicianAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ClinicianRoute,
} as any)
const ClinicianDocumentsRoute = ClinicianDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ClinicianRoute,
} as any)
const ClinicianPatientsRoute = ClinicianPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ClinicianRoute,
} as any)
const ClinicianSettingsRoute = ClinicianSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClinicianRoute,
} as any)
const ClinicianTimelineRoute = ClinicianTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ClinicianRoute,
} as any)
const ClinicianWorklistRoute = ClinicianWorklistRouteImport.update({
  id: '/worklist',
  path: '/worklist',
  getParentRoute: () => ClinicianRoute,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsDlqRoute = OperationsDlqRouteImport.update({
  id: '/dlq',
  path: '/dlq',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsManualReviewRoute = OperationsManualReviewRouteImport.update({
  id: '/manual-review',
  path: '/manual-review',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsOutboxRoute = OperationsOutboxRouteImport.update({
  id: '/outbox',
  path: '/outbox',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsReplayRoute = OperationsReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsSearchRoute = OperationsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => OperationsRoute,
} as any)
const PatientKioskIndexRoute = PatientKioskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientKioskRoute,
} as any)
const PatientKioskCaseTakingRoute = PatientKioskCaseTakingRouteImport.update({
  id: '/case-taking',
  path: '/case-taking',
  getParentRoute: () => PatientKioskRoute,
} as any)
const PatientKioskCompleteRoute = PatientKioskCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => PatientKioskRoute,
} as any)
const PatientKioskConfirmRoute = PatientKioskConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => PatientKioskRoute,
} as any)
const PatientKioskConsentRoute = PatientKioskConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => PatientKioskRoute,
} as any)
const PatientKioskConversationRoute =
  PatientKioskConversationRouteImport.update({
    id: '/conversation',
    path: '/conversation',
    getParentRoute: () => PatientKioskRoute,
  } as any)
const PatientKioskDocumentsRoute = PatientKioskDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PatientKioskRoute,
} as any)
const PatientKioskIdentificationRoute =
  PatientKioskIdentificationRouteImport.update({
    id: '/identification',
    path: '/identification',
    getParentRoute: () => PatientKioskRoute,
  } as any)
const PatientKioskIntroductionRoute =
  PatientKioskIntroductionRouteImport.update({
    id: '/introduction',
    path: '/introduction',
    getParentRoute: () => PatientKioskRoute,
  } as any)
const PatientKioskProcessingRoute = PatientKioskProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => PatientKioskRoute,
} as any)
const PatientKioskQuestionsRoute = PatientKioskQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => PatientKioskRoute,
} as any)
const PatientKioskReviewRoute = PatientKioskReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PatientKioskRoute,
} as any)
const PatientKioskVitalsRoute = PatientKioskVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => PatientKioskRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientConsentsRoute = PatientConsentsRouteImport.update({
  id: '/consents',
  path: '/consents',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDocumentsRoute = PatientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PatientRoute,
} as any)
const PatientIntakesRoute = PatientIntakesRouteImport.update({
  id: '/intakes',
  path: '/intakes',
  getParentRoute: () => PatientRoute,
} as any)
const PatientNotificationsRoute = PatientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PatientRoute,
} as any)
const PatientTimelineRoute = PatientTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => PatientRoute,
} as any)
const PatientIntakeRoute = PatientIntakeRouteImport.update({
  id: '/patient_/intake',
  path: '/patient/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicianPatientsIndexRoute = ClinicianPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicianPatientsRoute,
} as any)
const ClinicianPatientsIdRoute = ClinicianPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClinicianPatientsRoute,
} as any)
const ApiDocumentsDocumentIdFileRoute =
  ApiDocumentsDocumentIdFileRouteImport.update({
    id: '/api/documents/$documentId/file',
    path: '/api/documents/$documentId/file',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVoiceSpeakRoute = ApiPublicVoiceSpeakRouteImport.update({
  id: '/api/public/voice/speak',
  path: '/api/public/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceTranscribeRoute =
  ApiPublicVoiceTranscribeRouteImport.update({
    id: '/api/public/voice/transcribe',
    path: '/api/public/voice/transcribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClinicianPatientsIdSignRoute = ClinicianPatientsIdSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => ClinicianPatientsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assisted-kiosk': typeof AssistedKioskRouteWithChildren
  '/clinician': typeof ClinicianRouteWithChildren
  '/document-check': typeof DocumentCheckRoute
  '/operations': typeof OperationsRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/patient-kiosk': typeof PatientKioskRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/assisted-kiosk/case-taking': typeof AssistedKioskCaseTakingRoute
  '/assisted-kiosk/documents': typeof AssistedKioskDocumentsRoute
  '/assisted-kiosk/handoff': typeof AssistedKioskHandoffRoute
  '/assisted-kiosk/queue': typeof AssistedKioskQueueRoute
  '/assisted-kiosk/start': typeof AssistedKioskStartRoute
  '/assisted-kiosk/vitals': typeof AssistedKioskVitalsRoute
  '/clinician/alerts': typeof ClinicianAlertsRoute
  '/clinician/documents': typeof ClinicianDocumentsRoute
  '/clinician/patients': typeof ClinicianPatientsRouteWithChildren
  '/clinician/settings': typeof ClinicianSettingsRoute
  '/clinician/timeline': typeof ClinicianTimelineRoute
  '/clinician/worklist': typeof ClinicianWorklistRoute
  '/operations/dlq': typeof OperationsDlqRoute
  '/operations/manual-review': typeof OperationsManualReviewRoute
  '/operations/outbox': typeof OperationsOutboxRoute
  '/operations/replay': typeof OperationsReplayRoute
  '/operations/search': typeof OperationsSearchRoute
  '/patient-kiosk/case-taking': typeof PatientKioskCaseTakingRoute
  '/patient-kiosk/complete': typeof PatientKioskCompleteRoute
  '/patient-kiosk/confirm': typeof PatientKioskConfirmRoute
  '/patient-kiosk/consent': typeof PatientKioskConsentRoute
  '/patient-kiosk/conversation': typeof PatientKioskConversationRoute
  '/patient-kiosk/documents': typeof PatientKioskDocumentsRoute
  '/patient-kiosk/identification': typeof PatientKioskIdentificationRoute
  '/patient-kiosk/introduction': typeof PatientKioskIntroductionRoute
  '/patient-kiosk/processing': typeof PatientKioskProcessingRoute
  '/patient-kiosk/questions': typeof PatientKioskQuestionsRoute
  '/patient-kiosk/review': typeof PatientKioskReviewRoute
  '/patient-kiosk/vitals': typeof PatientKioskVitalsRoute
  '/patient/consents': typeof PatientConsentsRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/intakes': typeof PatientIntakesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/timeline': typeof PatientTimelineRoute
  '/patient/intake': typeof PatientIntakeRoute
  '/admin/': typeof AdminIndexRoute
  '/assisted-kiosk/': typeof AssistedKioskIndexRoute
  '/clinician/': typeof ClinicianIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/patient-kiosk/': typeof PatientKioskIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/clinician/patients/$id': typeof ClinicianPatientsIdRouteWithChildren
  '/clinician/patients/': typeof ClinicianPatientsIndexRoute
  '/api/documents/$documentId/file': typeof ApiDocumentsDocumentIdFileRoute
  '/api/public/voice/speak': typeof ApiPublicVoiceSpeakRoute
  '/api/public/voice/transcribe': typeof ApiPublicVoiceTranscribeRoute
  '/clinician/patients/$id/sign': typeof ClinicianPatientsIdSignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/document-check': typeof DocumentCheckRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/assisted-kiosk/case-taking': typeof AssistedKioskCaseTakingRoute
  '/assisted-kiosk/documents': typeof AssistedKioskDocumentsRoute
  '/assisted-kiosk/handoff': typeof AssistedKioskHandoffRoute
  '/assisted-kiosk/queue': typeof AssistedKioskQueueRoute
  '/assisted-kiosk/start': typeof AssistedKioskStartRoute
  '/assisted-kiosk/vitals': typeof AssistedKioskVitalsRoute
  '/clinician/alerts': typeof ClinicianAlertsRoute
  '/clinician/documents': typeof ClinicianDocumentsRoute
  '/clinician/settings': typeof ClinicianSettingsRoute
  '/clinician/timeline': typeof ClinicianTimelineRoute
  '/clinician/worklist': typeof ClinicianWorklistRoute
  '/operations/dlq': typeof OperationsDlqRoute
  '/operations/manual-review': typeof OperationsManualReviewRoute
  '/operations/outbox': typeof OperationsOutboxRoute
  '/operations/replay': typeof OperationsReplayRoute
  '/operations/search': typeof OperationsSearchRoute
  '/patient-kiosk/case-taking': typeof PatientKioskCaseTakingRoute
  '/patient-kiosk/complete': typeof PatientKioskCompleteRoute
  '/patient-kiosk/confirm': typeof PatientKioskConfirmRoute
  '/patient-kiosk/consent': typeof PatientKioskConsentRoute
  '/patient-kiosk/conversation': typeof PatientKioskConversationRoute
  '/patient-kiosk/documents': typeof PatientKioskDocumentsRoute
  '/patient-kiosk/identification': typeof PatientKioskIdentificationRoute
  '/patient-kiosk/introduction': typeof PatientKioskIntroductionRoute
  '/patient-kiosk/processing': typeof PatientKioskProcessingRoute
  '/patient-kiosk/questions': typeof PatientKioskQuestionsRoute
  '/patient-kiosk/review': typeof PatientKioskReviewRoute
  '/patient-kiosk/vitals': typeof PatientKioskVitalsRoute
  '/patient/consents': typeof PatientConsentsRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/intakes': typeof PatientIntakesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/timeline': typeof PatientTimelineRoute
  '/patient/intake': typeof PatientIntakeRoute
  '/admin': typeof AdminIndexRoute
  '/assisted-kiosk': typeof AssistedKioskIndexRoute
  '/clinician': typeof ClinicianIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/patient-kiosk': typeof PatientKioskIndexRoute
  '/patient': typeof PatientIndexRoute
  '/clinician/patients/$id': typeof ClinicianPatientsIdRouteWithChildren
  '/clinician/patients': typeof ClinicianPatientsIndexRoute
  '/api/documents/$documentId/file': typeof ApiDocumentsDocumentIdFileRoute
  '/api/public/voice/speak': typeof ApiPublicVoiceSpeakRoute
  '/api/public/voice/transcribe': typeof ApiPublicVoiceTranscribeRoute
  '/clinician/patients/$id/sign': typeof ClinicianPatientsIdSignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assisted-kiosk': typeof AssistedKioskRouteWithChildren
  '/clinician': typeof ClinicianRouteWithChildren
  '/document-check': typeof DocumentCheckRoute
  '/operations': typeof OperationsRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/patient-kiosk': typeof PatientKioskRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/assisted-kiosk/case-taking': typeof AssistedKioskCaseTakingRoute
  '/assisted-kiosk/documents': typeof AssistedKioskDocumentsRoute
  '/assisted-kiosk/handoff': typeof AssistedKioskHandoffRoute
  '/assisted-kiosk/queue': typeof AssistedKioskQueueRoute
  '/assisted-kiosk/start': typeof AssistedKioskStartRoute
  '/assisted-kiosk/vitals': typeof AssistedKioskVitalsRoute
  '/clinician/alerts': typeof ClinicianAlertsRoute
  '/clinician/documents': typeof ClinicianDocumentsRoute
  '/clinician/patients': typeof ClinicianPatientsRouteWithChildren
  '/clinician/settings': typeof ClinicianSettingsRoute
  '/clinician/timeline': typeof ClinicianTimelineRoute
  '/clinician/worklist': typeof ClinicianWorklistRoute
  '/operations/dlq': typeof OperationsDlqRoute
  '/operations/manual-review': typeof OperationsManualReviewRoute
  '/operations/outbox': typeof OperationsOutboxRoute
  '/operations/replay': typeof OperationsReplayRoute
  '/operations/search': typeof OperationsSearchRoute
  '/patient-kiosk/case-taking': typeof PatientKioskCaseTakingRoute
  '/patient-kiosk/complete': typeof PatientKioskCompleteRoute
  '/patient-kiosk/confirm': typeof PatientKioskConfirmRoute
  '/patient-kiosk/consent': typeof PatientKioskConsentRoute
  '/patient-kiosk/conversation': typeof PatientKioskConversationRoute
  '/patient-kiosk/documents': typeof PatientKioskDocumentsRoute
  '/patient-kiosk/identification': typeof PatientKioskIdentificationRoute
  '/patient-kiosk/introduction': typeof PatientKioskIntroductionRoute
  '/patient-kiosk/processing': typeof PatientKioskProcessingRoute
  '/patient-kiosk/questions': typeof PatientKioskQuestionsRoute
  '/patient-kiosk/review': typeof PatientKioskReviewRoute
  '/patient-kiosk/vitals': typeof PatientKioskVitalsRoute
  '/patient/consents': typeof PatientConsentsRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/intakes': typeof PatientIntakesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/timeline': typeof PatientTimelineRoute
  '/patient_/intake': typeof PatientIntakeRoute
  '/admin/': typeof AdminIndexRoute
  '/assisted-kiosk/': typeof AssistedKioskIndexRoute
  '/clinician/': typeof ClinicianIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/patient-kiosk/': typeof PatientKioskIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/clinician/patients/$id': typeof ClinicianPatientsIdRouteWithChildren
  '/clinician/patients/': typeof ClinicianPatientsIndexRoute
  '/api/documents/$documentId/file': typeof ApiDocumentsDocumentIdFileRoute
  '/api/public/voice/speak': typeof ApiPublicVoiceSpeakRoute
  '/api/public/voice/transcribe': typeof ApiPublicVoiceTranscribeRoute
  '/clinician/patients/$id/sign': typeof ClinicianPatientsIdSignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assisted-kiosk'
    | '/clinician'
    | '/document-check'
    | '/operations'
    | '/patient'
    | '/patient-kiosk'
    | '/sign-in'
    | '/sign-up'
    | '/admin/audit'
    | '/admin/configuration'
    | '/admin/facilities'
    | '/admin/roles'
    | '/admin/users'
    | '/assisted-kiosk/case-taking'
    | '/assisted-kiosk/documents'
    | '/assisted-kiosk/handoff'
    | '/assisted-kiosk/queue'
    | '/assisted-kiosk/start'
    | '/assisted-kiosk/vitals'
    | '/clinician/alerts'
    | '/clinician/documents'
    | '/clinician/patients'
    | '/clinician/settings'
    | '/clinician/timeline'
    | '/clinician/worklist'
    | '/operations/dlq'
    | '/operations/manual-review'
    | '/operations/outbox'
    | '/operations/replay'
    | '/operations/search'
    | '/patient-kiosk/case-taking'
    | '/patient-kiosk/complete'
    | '/patient-kiosk/confirm'
    | '/patient-kiosk/consent'
    | '/patient-kiosk/conversation'
    | '/patient-kiosk/documents'
    | '/patient-kiosk/identification'
    | '/patient-kiosk/introduction'
    | '/patient-kiosk/processing'
    | '/patient-kiosk/questions'
    | '/patient-kiosk/review'
    | '/patient-kiosk/vitals'
    | '/patient/consents'
    | '/patient/documents'
    | '/patient/intakes'
    | '/patient/notifications'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/timeline'
    | '/patient/intake'
    | '/admin/'
    | '/assisted-kiosk/'
    | '/clinician/'
    | '/operations/'
    | '/patient-kiosk/'
    | '/patient/'
    | '/clinician/patients/$id'
    | '/clinician/patients/'
    | '/api/documents/$documentId/file'
    | '/api/public/voice/speak'
    | '/api/public/voice/transcribe'
    | '/clinician/patients/$id/sign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/document-check'
    | '/sign-in'
    | '/sign-up'
    | '/admin/audit'
    | '/admin/configuration'
    | '/admin/facilities'
    | '/admin/roles'
    | '/admin/users'
    | '/assisted-kiosk/case-taking'
    | '/assisted-kiosk/documents'
    | '/assisted-kiosk/handoff'
    | '/assisted-kiosk/queue'
    | '/assisted-kiosk/start'
    | '/assisted-kiosk/vitals'
    | '/clinician/alerts'
    | '/clinician/documents'
    | '/clinician/settings'
    | '/clinician/timeline'
    | '/clinician/worklist'
    | '/operations/dlq'
    | '/operations/manual-review'
    | '/operations/outbox'
    | '/operations/replay'
    | '/operations/search'
    | '/patient-kiosk/case-taking'
    | '/patient-kiosk/complete'
    | '/patient-kiosk/confirm'
    | '/patient-kiosk/consent'
    | '/patient-kiosk/conversation'
    | '/patient-kiosk/documents'
    | '/patient-kiosk/identification'
    | '/patient-kiosk/introduction'
    | '/patient-kiosk/processing'
    | '/patient-kiosk/questions'
    | '/patient-kiosk/review'
    | '/patient-kiosk/vitals'
    | '/patient/consents'
    | '/patient/documents'
    | '/patient/intakes'
    | '/patient/notifications'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/timeline'
    | '/patient/intake'
    | '/admin'
    | '/assisted-kiosk'
    | '/clinician'
    | '/operations'
    | '/patient-kiosk'
    | '/patient'
    | '/clinician/patients/$id'
    | '/clinician/patients'
    | '/api/documents/$documentId/file'
    | '/api/public/voice/speak'
    | '/api/public/voice/transcribe'
    | '/clinician/patients/$id/sign'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assisted-kiosk'
    | '/clinician'
    | '/document-check'
    | '/operations'
    | '/patient'
    | '/patient-kiosk'
    | '/sign-in'
    | '/sign-up'
    | '/admin/audit'
    | '/admin/configuration'
    | '/admin/facilities'
    | '/admin/roles'
    | '/admin/users'
    | '/assisted-kiosk/case-taking'
    | '/assisted-kiosk/documents'
    | '/assisted-kiosk/handoff'
    | '/assisted-kiosk/queue'
    | '/assisted-kiosk/start'
    | '/assisted-kiosk/vitals'
    | '/clinician/alerts'
    | '/clinician/documents'
    | '/clinician/patients'
    | '/clinician/settings'
    | '/clinician/timeline'
    | '/clinician/worklist'
    | '/operations/dlq'
    | '/operations/manual-review'
    | '/operations/outbox'
    | '/operations/replay'
    | '/operations/search'
    | '/patient-kiosk/case-taking'
    | '/patient-kiosk/complete'
    | '/patient-kiosk/confirm'
    | '/patient-kiosk/consent'
    | '/patient-kiosk/conversation'
    | '/patient-kiosk/documents'
    | '/patient-kiosk/identification'
    | '/patient-kiosk/introduction'
    | '/patient-kiosk/processing'
    | '/patient-kiosk/questions'
    | '/patient-kiosk/review'
    | '/patient-kiosk/vitals'
    | '/patient/consents'
    | '/patient/documents'
    | '/patient/intakes'
    | '/patient/notifications'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/timeline'
    | '/patient_/intake'
    | '/admin/'
    | '/assisted-kiosk/'
    | '/clinician/'
    | '/operations/'
    | '/patient-kiosk/'
    | '/patient/'
    | '/clinician/patients/$id'
    | '/clinician/patients/'
    | '/api/documents/$documentId/file'
    | '/api/public/voice/speak'
    | '/api/public/voice/transcribe'
    | '/clinician/patients/$id/sign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistedKioskRoute: typeof AssistedKioskRouteWithChildren
  ClinicianRoute: typeof ClinicianRouteWithChildren
  DocumentCheckRoute: typeof DocumentCheckRoute
  OperationsRoute: typeof OperationsRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  PatientKioskRoute: typeof PatientKioskRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  PatientIntakeRoute: typeof PatientIntakeRoute
  ApiDocumentsDocumentIdFileRoute: typeof ApiDocumentsDocumentIdFileRoute
  ApiPublicVoiceSpeakRoute: typeof ApiPublicVoiceSpeakRoute
  ApiPublicVoiceTranscribeRoute: typeof ApiPublicVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assisted-kiosk': {
      id: '/assisted-kiosk'
      path: '/assisted-kiosk'
      fullPath: '/assisted-kiosk'
      preLoaderRoute: typeof AssistedKioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician': {
      id: '/clinician'
      path: '/clinician'
      fullPath: '/clinician'
      preLoaderRoute: typeof ClinicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-check': {
      id: '/document-check'
      path: '/document-check'
      fullPath: '/document-check'
      preLoaderRoute: typeof DocumentCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-kiosk': {
      id: '/patient-kiosk'
      path: '/patient-kiosk'
      fullPath: '/patient-kiosk'
      preLoaderRoute: typeof PatientKioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuration': {
      id: '/admin/configuration'
      path: '/configuration'
      fullPath: '/admin/configuration'
      preLoaderRoute: typeof AdminConfigurationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facilities': {
      id: '/admin/facilities'
      path: '/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/assisted-kiosk/': {
      id: '/assisted-kiosk/'
      path: '/'
      fullPath: '/assisted-kiosk/'
      preLoaderRoute: typeof AssistedKioskIndexRouteImport
      parentRoute: typeof AssistedKioskRoute
    }
    '/assisted-kiosk/case-taking': {
      id: '/assisted-kiosk/case-taking'
      path: '/case-taking'
      fullPath: '/assisted-kiosk/case-taking'
      preLoaderRoute: typeof AssistedKioskCaseTakingRouteImport
      parentRoute: typeof AssistedKioskRoute
    }
    '/assisted-kiosk/documents': {
      id: '/assisted-kiosk/documents'
      path: '/documents'
      fullPath: '/assisted-kiosk/documents'
      preLoaderRoute: typeof AssistedKioskDocumentsRouteImport
      parentRoute: typeof AssistedKioskRoute
    }
    '/assisted-kiosk/handoff': {
      id: '/assisted-kiosk/handoff'
      path: '/handoff'
      fullPath: '/assisted-kiosk/handoff'
      preLoaderRoute: typeof AssistedKioskHandoffRouteImport
      parentRoute: typeof AssistedKioskRoute
    }
    '/assisted-kiosk/queue': {
      id: '/assisted-kiosk/queue'
      path: '/queue'
      fullPath: '/assisted-kiosk/queue'
      preLoaderRoute: typeof AssistedKioskQueueRouteImport
      parentRoute: typeof AssistedKioskRoute
    }
    '/assisted-kiosk/start': {
      id: '/assisted-kiosk/start'
      path: '/start'
      fullPath: '/assisted-kiosk/start'
      preLoaderRoute: typeof AssistedKioskStartRouteImport
      parentRoute: typeof AssistedKioskRoute
    }
    '/assisted-kiosk/vitals': {
      id: '/assisted-kiosk/vitals'
      path: '/vitals'
      fullPath: '/assisted-kiosk/vitals'
      preLoaderRoute: typeof AssistedKioskVitalsRouteImport
      parentRoute: typeof AssistedKioskRoute
    }
    '/clinician/': {
      id: '/clinician/'
      path: '/'
      fullPath: '/clinician/'
      preLoaderRoute: typeof ClinicianIndexRouteImport
      parentRoute: typeof ClinicianRoute
    }
    '/clinician/alerts': {
      id: '/clinician/alerts'
      path: '/alerts'
      fullPath: '/clinician/alerts'
      preLoaderRoute: typeof ClinicianAlertsRouteImport
      parentRoute: typeof ClinicianRoute
    }
    '/clinician/documents': {
      id: '/clinician/documents'
      path: '/documents'
      fullPath: '/clinician/documents'
      preLoaderRoute: typeof ClinicianDocumentsRouteImport
      parentRoute: typeof ClinicianRoute
    }
    '/clinician/patients': {
      id: '/clinician/patients'
      path: '/patients'
      fullPath: '/clinician/patients'
      preLoaderRoute: typeof ClinicianPatientsRouteImport
      parentRoute: typeof ClinicianRoute
    }
    '/clinician/settings': {
      id: '/clinician/settings'
      path: '/settings'
      fullPath: '/clinician/settings'
      preLoaderRoute: typeof ClinicianSettingsRouteImport
      parentRoute: typeof ClinicianRoute
    }
    '/clinician/timeline': {
      id: '/clinician/timeline'
      path: '/timeline'
      fullPath: '/clinician/timeline'
      preLoaderRoute: typeof ClinicianTimelineRouteImport
      parentRoute: typeof ClinicianRoute
    }
    '/clinician/worklist': {
      id: '/clinician/worklist'
      path: '/worklist'
      fullPath: '/clinician/worklist'
      preLoaderRoute: typeof ClinicianWorklistRouteImport
      parentRoute: typeof ClinicianRoute
    }
    '/operations/': {
      id: '/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/dlq': {
      id: '/operations/dlq'
      path: '/dlq'
      fullPath: '/operations/dlq'
      preLoaderRoute: typeof OperationsDlqRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/manual-review': {
      id: '/operations/manual-review'
      path: '/manual-review'
      fullPath: '/operations/manual-review'
      preLoaderRoute: typeof OperationsManualReviewRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/outbox': {
      id: '/operations/outbox'
      path: '/outbox'
      fullPath: '/operations/outbox'
      preLoaderRoute: typeof OperationsOutboxRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/replay': {
      id: '/operations/replay'
      path: '/replay'
      fullPath: '/operations/replay'
      preLoaderRoute: typeof OperationsReplayRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/search': {
      id: '/operations/search'
      path: '/search'
      fullPath: '/operations/search'
      preLoaderRoute: typeof OperationsSearchRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/patient-kiosk/': {
      id: '/patient-kiosk/'
      path: '/'
      fullPath: '/patient-kiosk/'
      preLoaderRoute: typeof PatientKioskIndexRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/case-taking': {
      id: '/patient-kiosk/case-taking'
      path: '/case-taking'
      fullPath: '/patient-kiosk/case-taking'
      preLoaderRoute: typeof PatientKioskCaseTakingRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/complete': {
      id: '/patient-kiosk/complete'
      path: '/complete'
      fullPath: '/patient-kiosk/complete'
      preLoaderRoute: typeof PatientKioskCompleteRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/confirm': {
      id: '/patient-kiosk/confirm'
      path: '/confirm'
      fullPath: '/patient-kiosk/confirm'
      preLoaderRoute: typeof PatientKioskConfirmRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/consent': {
      id: '/patient-kiosk/consent'
      path: '/consent'
      fullPath: '/patient-kiosk/consent'
      preLoaderRoute: typeof PatientKioskConsentRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/conversation': {
      id: '/patient-kiosk/conversation'
      path: '/conversation'
      fullPath: '/patient-kiosk/conversation'
      preLoaderRoute: typeof PatientKioskConversationRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/documents': {
      id: '/patient-kiosk/documents'
      path: '/documents'
      fullPath: '/patient-kiosk/documents'
      preLoaderRoute: typeof PatientKioskDocumentsRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/identification': {
      id: '/patient-kiosk/identification'
      path: '/identification'
      fullPath: '/patient-kiosk/identification'
      preLoaderRoute: typeof PatientKioskIdentificationRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/introduction': {
      id: '/patient-kiosk/introduction'
      path: '/introduction'
      fullPath: '/patient-kiosk/introduction'
      preLoaderRoute: typeof PatientKioskIntroductionRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/processing': {
      id: '/patient-kiosk/processing'
      path: '/processing'
      fullPath: '/patient-kiosk/processing'
      preLoaderRoute: typeof PatientKioskProcessingRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/questions': {
      id: '/patient-kiosk/questions'
      path: '/questions'
      fullPath: '/patient-kiosk/questions'
      preLoaderRoute: typeof PatientKioskQuestionsRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/review': {
      id: '/patient-kiosk/review'
      path: '/review'
      fullPath: '/patient-kiosk/review'
      preLoaderRoute: typeof PatientKioskReviewRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient-kiosk/vitals': {
      id: '/patient-kiosk/vitals'
      path: '/vitals'
      fullPath: '/patient-kiosk/vitals'
      preLoaderRoute: typeof PatientKioskVitalsRouteImport
      parentRoute: typeof PatientKioskRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/consents': {
      id: '/patient/consents'
      path: '/consents'
      fullPath: '/patient/consents'
      preLoaderRoute: typeof PatientConsentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/documents': {
      id: '/patient/documents'
      path: '/documents'
      fullPath: '/patient/documents'
      preLoaderRoute: typeof PatientDocumentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/intakes': {
      id: '/patient/intakes'
      path: '/intakes'
      fullPath: '/patient/intakes'
      preLoaderRoute: typeof PatientIntakesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/notifications': {
      id: '/patient/notifications'
      path: '/notifications'
      fullPath: '/patient/notifications'
      preLoaderRoute: typeof PatientNotificationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/timeline': {
      id: '/patient/timeline'
      path: '/timeline'
      fullPath: '/patient/timeline'
      preLoaderRoute: typeof PatientTimelineRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient_/intake': {
      id: '/patient_/intake'
      path: '/patient/intake'
      fullPath: '/patient/intake'
      preLoaderRoute: typeof PatientIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician/patients/': {
      id: '/clinician/patients/'
      path: '/'
      fullPath: '/clinician/patients/'
      preLoaderRoute: typeof ClinicianPatientsIndexRouteImport
      parentRoute: typeof ClinicianPatientsRoute
    }
    '/clinician/patients/$id': {
      id: '/clinician/patients/$id'
      path: '/$id'
      fullPath: '/clinician/patients/$id'
      preLoaderRoute: typeof ClinicianPatientsIdRouteImport
      parentRoute: typeof ClinicianPatientsRoute
    }
    '/api/documents/$documentId/file': {
      id: '/api/documents/$documentId/file'
      path: '/api/documents/$documentId/file'
      fullPath: '/api/documents/$documentId/file'
      preLoaderRoute: typeof ApiDocumentsDocumentIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice/speak': {
      id: '/api/public/voice/speak'
      path: '/api/public/voice/speak'
      fullPath: '/api/public/voice/speak'
      preLoaderRoute: typeof ApiPublicVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice/transcribe': {
      id: '/api/public/voice/transcribe'
      path: '/api/public/voice/transcribe'
      fullPath: '/api/public/voice/transcribe'
      preLoaderRoute: typeof ApiPublicVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician/patients/$id/sign': {
      id: '/clinician/patients/$id/sign'
      path: '/sign'
      fullPath: '/clinician/patients/$id/sign'
      preLoaderRoute: typeof ClinicianPatientsIdSignRouteImport
      parentRoute: typeof ClinicianPatientsIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminConfigurationRoute: typeof AdminConfigurationRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminConfigurationRoute: AdminConfigurationRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AssistedKioskRouteChildren {
  AssistedKioskCaseTakingRoute: typeof AssistedKioskCaseTakingRoute
  AssistedKioskDocumentsRoute: typeof AssistedKioskDocumentsRoute
  AssistedKioskHandoffRoute: typeof AssistedKioskHandoffRoute
  AssistedKioskQueueRoute: typeof AssistedKioskQueueRoute
  AssistedKioskStartRoute: typeof AssistedKioskStartRoute
  AssistedKioskVitalsRoute: typeof AssistedKioskVitalsRoute
  AssistedKioskIndexRoute: typeof AssistedKioskIndexRoute
}

const AssistedKioskRouteChildren: AssistedKioskRouteChildren = {
  AssistedKioskCaseTakingRoute: AssistedKioskCaseTakingRoute,
  AssistedKioskDocumentsRoute: AssistedKioskDocumentsRoute,
  AssistedKioskHandoffRoute: AssistedKioskHandoffRoute,
  AssistedKioskQueueRoute: AssistedKioskQueueRoute,
  AssistedKioskStartRoute: AssistedKioskStartRoute,
  AssistedKioskVitalsRoute: AssistedKioskVitalsRoute,
  AssistedKioskIndexRoute: AssistedKioskIndexRoute,
}

const AssistedKioskRouteWithChildren = AssistedKioskRoute._addFileChildren(
  AssistedKioskRouteChildren,
)

interface ClinicianPatientsIdRouteChildren {
  ClinicianPatientsIdSignRoute: typeof ClinicianPatientsIdSignRoute
}

const ClinicianPatientsIdRouteChildren: ClinicianPatientsIdRouteChildren = {
  ClinicianPatientsIdSignRoute: ClinicianPatientsIdSignRoute,
}

const ClinicianPatientsIdRouteWithChildren =
  ClinicianPatientsIdRoute._addFileChildren(ClinicianPatientsIdRouteChildren)

interface ClinicianPatientsRouteChildren {
  ClinicianPatientsIdRoute: typeof ClinicianPatientsIdRouteWithChildren
  ClinicianPatientsIndexRoute: typeof ClinicianPatientsIndexRoute
}

const ClinicianPatientsRouteChildren: ClinicianPatientsRouteChildren = {
  ClinicianPatientsIdRoute: ClinicianPatientsIdRouteWithChildren,
  ClinicianPatientsIndexRoute: ClinicianPatientsIndexRoute,
}

const ClinicianPatientsRouteWithChildren =
  ClinicianPatientsRoute._addFileChildren(ClinicianPatientsRouteChildren)

interface ClinicianRouteChildren {
  ClinicianAlertsRoute: typeof ClinicianAlertsRoute
  ClinicianDocumentsRoute: typeof ClinicianDocumentsRoute
  ClinicianPatientsRoute: typeof ClinicianPatientsRouteWithChildren
  ClinicianSettingsRoute: typeof ClinicianSettingsRoute
  ClinicianTimelineRoute: typeof ClinicianTimelineRoute
  ClinicianWorklistRoute: typeof ClinicianWorklistRoute
  ClinicianIndexRoute: typeof ClinicianIndexRoute
}

const ClinicianRouteChildren: ClinicianRouteChildren = {
  ClinicianAlertsRoute: ClinicianAlertsRoute,
  ClinicianDocumentsRoute: ClinicianDocumentsRoute,
  ClinicianPatientsRoute: ClinicianPatientsRouteWithChildren,
  ClinicianSettingsRoute: ClinicianSettingsRoute,
  ClinicianTimelineRoute: ClinicianTimelineRoute,
  ClinicianWorklistRoute: ClinicianWorklistRoute,
  ClinicianIndexRoute: ClinicianIndexRoute,
}

const ClinicianRouteWithChildren = ClinicianRoute._addFileChildren(
  ClinicianRouteChildren,
)

interface OperationsRouteChildren {
  OperationsDlqRoute: typeof OperationsDlqRoute
  OperationsManualReviewRoute: typeof OperationsManualReviewRoute
  OperationsOutboxRoute: typeof OperationsOutboxRoute
  OperationsReplayRoute: typeof OperationsReplayRoute
  OperationsSearchRoute: typeof OperationsSearchRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsDlqRoute: OperationsDlqRoute,
  OperationsManualReviewRoute: OperationsManualReviewRoute,
  OperationsOutboxRoute: OperationsOutboxRoute,
  OperationsReplayRoute: OperationsReplayRoute,
  OperationsSearchRoute: OperationsSearchRoute,
  OperationsIndexRoute: OperationsIndexRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

interface PatientRouteChildren {
  PatientConsentsRoute: typeof PatientConsentsRoute
  PatientDocumentsRoute: typeof PatientDocumentsRoute
  PatientIntakesRoute: typeof PatientIntakesRoute
  PatientNotificationsRoute: typeof PatientNotificationsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientReportsRoute: typeof PatientReportsRoute
  PatientTimelineRoute: typeof PatientTimelineRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientConsentsRoute: PatientConsentsRoute,
  PatientDocumentsRoute: PatientDocumentsRoute,
  PatientIntakesRoute: PatientIntakesRoute,
  PatientNotificationsRoute: PatientNotificationsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientReportsRoute: PatientReportsRoute,
  PatientTimelineRoute: PatientTimelineRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PatientKioskRouteChildren {
  PatientKioskCaseTakingRoute: typeof PatientKioskCaseTakingRoute
  PatientKioskCompleteRoute: typeof PatientKioskCompleteRoute
  PatientKioskConfirmRoute: typeof PatientKioskConfirmRoute
  PatientKioskConsentRoute: typeof PatientKioskConsentRoute
  PatientKioskConversationRoute: typeof PatientKioskConversationRoute
  PatientKioskDocumentsRoute: typeof PatientKioskDocumentsRoute
  PatientKioskIdentificationRoute: typeof PatientKioskIdentificationRoute
  PatientKioskIntroductionRoute: typeof PatientKioskIntroductionRoute
  PatientKioskProcessingRoute: typeof PatientKioskProcessingRoute
  PatientKioskQuestionsRoute: typeof PatientKioskQuestionsRoute
  PatientKioskReviewRoute: typeof PatientKioskReviewRoute
  PatientKioskVitalsRoute: typeof PatientKioskVitalsRoute
  PatientKioskIndexRoute: typeof PatientKioskIndexRoute
}

const PatientKioskRouteChildren: PatientKioskRouteChildren = {
  PatientKioskCaseTakingRoute: PatientKioskCaseTakingRoute,
  PatientKioskCompleteRoute: PatientKioskCompleteRoute,
  PatientKioskConfirmRoute: PatientKioskConfirmRoute,
  PatientKioskConsentRoute: PatientKioskConsentRoute,
  PatientKioskConversationRoute: PatientKioskConversationRoute,
  PatientKioskDocumentsRoute: PatientKioskDocumentsRoute,
  PatientKioskIdentificationRoute: PatientKioskIdentificationRoute,
  PatientKioskIntroductionRoute: PatientKioskIntroductionRoute,
  PatientKioskProcessingRoute: PatientKioskProcessingRoute,
  PatientKioskQuestionsRoute: PatientKioskQuestionsRoute,
  PatientKioskReviewRoute: PatientKioskReviewRoute,
  PatientKioskVitalsRoute: PatientKioskVitalsRoute,
  PatientKioskIndexRoute: PatientKioskIndexRoute,
}

const PatientKioskRouteWithChildren = PatientKioskRoute._addFileChildren(
  PatientKioskRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistedKioskRoute: AssistedKioskRouteWithChildren,
  ClinicianRoute: ClinicianRouteWithChildren,
  DocumentCheckRoute: DocumentCheckRoute,
  OperationsRoute: OperationsRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  PatientKioskRoute: PatientKioskRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  PatientIntakeRoute: PatientIntakeRoute,
  ApiDocumentsDocumentIdFileRoute: ApiDocumentsDocumentIdFileRoute,
  ApiPublicVoiceSpeakRoute: ApiPublicVoiceSpeakRoute,
  ApiPublicVoiceTranscribeRoute: ApiPublicVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
